version: "3.8"
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mysql
volumes:
  mysql_data: